### ISSUE TITLE
Having tests in a separate repo

### ISSUE THREAD

**Issue by dantudor** [php-ds/polyfill#1]
Hi @rtheunissen.

I've forked and cloned both the ployfill and tests repositories and looking to start the implementation. 

If we are to support php5.6 then we need to remove scalar type hinting and return type declarations. Doing this has highlighted to me a problem with having the tests in a separate repo. 

For me to work on the polyfill and also run the tests I've done the following:
1. Cloned the polyfill
2. Autoload the tests using composer autoload-dev 
3. Created a new phpunit.xml file in the polyfill that uses composer/autoload.php as the bootstrap.

At this stage I can run tests (albeit failing).

But to work on the tests I need to use my fork of the tests repo. After running composer, I removed the contents of ./vendor/php-ds/tests and symlinked my fork of the test repo to that location. 
Now I can update tests as I modify the polyfill but this process is terrible. 

When it then comes to creating a pull request I'd need to create requests for both the tests and polyfill. Then the CI will need a way to combine the repos together correctly to confirm the code is sound and the merge can be accepted.

I can't see how that this can work in a way that people will be able to contribute without having the tests committed directly in the polyfill.

What are your thoughts?

**Comment by rtheunissen** [comment]
> If we are to support php5.6 then we need to remove scalar type hinting and return type declarations. 

That may have been my biggest amateur moment in history. Won't be supporting 5.6 because of that, so we can just focus on >=7.0

> When it then comes to creating a pull request I'd need to create requests for both the tests and polyfill. 

The theory is that you shouldn't need to update any tests. If a test is broken or added, it should be a patch version on the tests repo. The difficult part is how to check that changes to the tests are correct without breaking the master builds of the extension and the polyfill. One solution would be to set up CI for the tests to pull in both the polyfill and the extension at the equivalent minor level, and check that everything passes.

> For me to work on the polyfill and also run the tests I've done the following:
1. Cloned the polyfill
2. Autoload the tests using composer autoload-dev 
3. Created a new phpunit.xml file in the polyfill that uses composer/autoload.php as the bootstrap.

This is no longer necessary. All you need to do is:

```bash
composer install
composer run-script test
```

No need for the extra `phpunit.xml` either. :)

However, if you want to (or have to) work on the tests at the same time, I think the symlink approach is the only solution.
