### ISSUE TITLE
If the polyfill is installed when the extension is available, which of both is used?

### ISSUE THREAD

**Issue by castarco** [php-ds/polyfill#33]
Hello,

If the polyfill is installed when the extension is available, which of both is used? Is the polyfill code prepared to give preference to the extension classes?

**Comment by rtheunissen** [comment]
The extension comes first.

This is because the classes are already loaded through the extension, so there's no attempt to autoload them, as would be the case if they are not loaded. The nice thing about this is that you can get significant performance gains simply by installing the extension, and not changing your config or code at all.
